services:
  api_anmerastore:
    build: .
    container_name: anmerastore_api
    ports:
      - ${PORT}:${PORT}
    environment:
      - PORT=${PORT}
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_PORT=${DB_PORT}
      - DB_NAME_BASEADMIN=${DB_NAME_BASEADMIN}
      - NODE_ENV=develonment
    restart: always